version: 2.1

# define defaults for usage same docker image
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xms3g -Xmx3g
    GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - persist_to_workspace:
                root: .
                paths:
                    - .

    decode_json:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Decode json
                command: echo $GOOGLE_SERVICES_JSON | base64 --decode --ignore-garbage > app/google-services.json
            - persist_to_workspace:
                root: .
                paths:
                    - .

    download_dependencies:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - restore_cache:
                keys:
                    - jars-cache-v1-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            # add permission avoid failure
            - run:
                name: Chmod permissions
                command: sudo chmod +x ./gradlew
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - save_cache:
                paths:
                    - ~/.gradle
                key: jars-cache-v1-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

    check:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            # for danger
            - restore_cache:
                keys:
                    - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
                    - gem-cache-v1-{{ arch }}-{{ .Branch }}
                    - gem-cache-v1
            - run:
                name: Bundle Install
                command: bundle install --path vendor/bundle --clean --jobs=2 --retry=3
            - save_cache:
                key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
            # add permission avoid failure
            - run:
                name: Chmod permissions
                command: sudo chmod +x ./gradlew
            # Run Tests and store results.
            # Separate Tests to avoid OOM.
            - run:
                name: Run lint
                command: ./gradlew lint
            - run:
                name: Run Tests
                command: ./gradlew test
            - run:
                name: Run ktlintcheck
                command: ./gradlew ktlintcheck
            - run:
                name: Run Danger
                command: bundle exec danger
                when: always
            - store_artifacts:
                path: app/build/reports
                destination: reports
            - store_test_results:
                path: app/build/test-results
            - persist_to_workspace:
                root: .
                paths:
                    - .

    deploy_debug:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            # add permission avoid failure
            - run:
                name: Chmod permissions
                command: sudo chmod +x ./gradlew
            # build
            - run:
                name: Build
                command: ./gradlew uploadDeployGateDebug
            - persist_to_workspace:
                root: .
                paths:
                    - .

    deploy_release:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            # add permission avoid failure
            - run:
                name: Chmod permissions
                command: sudo chmod +x ./gradlew
            # build
            - run:
                name: Build
                command: ./gradlew uploadDeployGateRelease
            - persist_to_workspace:
                root: .
                paths:
                    - .

workflows:
    version: 2
    build:
        jobs:
            - checkout
            - decode_json:
                requires:
                    - checkout
            - download_dependencies:
                requires:
                    - checkout
            - check:
                requires:
                    - decode_json
                    - download_dependencies
            - deploy_release:
                requires:
                    - check
                filters:
                    branches:
                        only:
                            - master
