opt_out_usage

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
      task: "test"
    )
  end

  desc "Runs lint"
  lane :lint do
    gradle(
      task: "lint"
    )
  end

  desc "Runs ktlint"
  lane :ktlint do
    gradle(
      task: "ktlintcheck"
    )
  end

  desc "Runs all checks"
  lane :all_checks do
    test
    lint
    ktlint
  end

  desc "Submit a new Beta Build to DeployGate"
  lane :beta do
    gradle(
      task: "clean assemble",
      build_type: "Release"
    )
    changelog_from_git_commits(
      between: ["develop", "HEAD"],
      date_format: "short",
      merge_commit_filtering: 'exclude_merges'
    )
    deploygate(
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}",
      message: "Git commits:\n\n#{lane_context[SharedValues::FL_CHANGELOG]}"
    )
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
